import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect } from "react";
import useCars from "hooks/useCars";
import styles from "../styles/Home.module.css";
import Cars from "containers/cars";

const Home: NextPage = () => {
  const router = useRouter();
  const { data, loading } = useCars();

  useEffect(() => {
    if (router.query.data) {
      // @ts-ignore
      const url = JSON.parse(router.query.data).link;
      window.location.assign(url);
    }
  }, [router]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Cars24</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Cars24 Unbooked Cars!</a>
        </h1>

        <div className={styles.grid}>
          {!loading ? <Cars data={data} /> : <div>Loading...</div>}
        </div>
      </main>

      <footer className={styles.footer}>
        <a target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
